title: .
description: .
url: "https://github.com/KyryloRubtsov/backup-lending/blob/main/index.html"
baseurl: "/git@github.com:KyryloRubtsov/backup-lending.git"

theme: minima

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag